import '@testing-library/jest-dom/vitest';

process.env.NEXT_PUBLIC_SOROBAN_RPC_URL = process.env.NEXT_PUBLIC_SOROBAN_RPC_URL || 'https://soroban-testnet.stellar.org';
process.env.NEXT_PUBLIC_SOROBAN_NETWORK_PASSPHRASE = process.env.NEXT_PUBLIC_SOROBAN_NETWORK_PASSPHRASE || 'Test SDF Network ; September 2015';
process.env.NEXT_PUBLIC_VAULT_CONTRACT_ID = process.env.NEXT_PUBLIC_VAULT_CONTRACT_ID && process.env.NEXT_PUBLIC_VAULT_CONTRACT_ID.startsWith('C') && process.env.NEXT_PUBLIC_VAULT_CONTRACT_ID !== 'CDLZFC3SYJYD7M6LJEFAPCHRLHAFKP6WYTHRF3EGO5CYD3EP4GZGM37T'
  ? process.env.NEXT_PUBLIC_VAULT_CONTRACT_ID
  : 'CAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABSC4';

